login:
  oauth:
    check: false

app:
  IMChat-server:
    url-prefix: http://IMChat-server
    serverAddr: localhost:9007

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 30000

spring:
  thymeleaf:
    cache: false
  session:
    store-type : none
  application:
    name: IMChat-web
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
      enabled: true

server:
  session:
    timeout: 3000
  port: 9001
  tomcat:
    max-connections: 60
    max-threads: 60
    accept-count: 60
security:
  basic:
    enabled: false

eureka:
  instance:
    #prefer-ip-address: true
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:10080/eureka/

zuul:
  host:
    max-per-route-connections: 20
    max-total-connections: 200
  routes:
    IMChat-server:
      path: /IMChat-server/**
      #serviceId: IMChat-server
      url: http://localhost:9007

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000